name: CI
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    uses: RiddimSoftware/riddim-release/.github/workflows/swift-package-build.yml@main
  success:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: |
          if [ "${{ needs.build.result }}" != "success" ]; then
            exit 1
          fi
